OWNERS
=> new: add owners file

meeting-notes/2019-Jun-06.md
=> new: report of June 6th meeting

meeting-notes/2019-Jun-13.md
Adding meeting notes for the 2019-06-13 meeting.
Signed-off-by: Michael Ducy <michael@ducy.org>
=> add meeting notes for 20190613

meeting-notes/2019-jun-28.md
=> docs: meeting minutes 2019 Jun 28th

.github/ISSUE_TEMPLATE.md, DEBUGGING_HOURS.md, README.md
Added the debugging hours as proposed in today's office hours!
=> docs: add description about debugging hours

.gitignore, OWNERS
Adding @markyjackson-taulia as a new reviewer.
Plus an initial `.gitignore` file.
=> new: reviewer (Marky Jackson)

meeting-notes/2019-Jul-04.md, meeting-notes/2019-Jul-11.md, meeting-notes/2019-Jun-20.md, meeting-notes/2019-jun-28.md
Signed-off-by: Michael Ducy <michael@ducy.org>
=> Add 20190711, fix dates in other notes

README.md
=> Removing broken calendar link

README.md
Signed-off-by: markyjackson-taulia <marky.r.jackson@gmail.com>
=> Adding new CNCF calendar, mailing list and slack links

meeting-notes/2019-Sep-04.md
=> new: meeting minutes of the Sep 4th 2019 office hours

live-streams/README.md
=> Adding live stream framework

meeting-notes/2019-10-09.md
Signed-off-by: markyjackson-taulia <marky.r.jackson@gmail.com>
=> Adding meeting notes from repo planning call 10/9/2019

meeting-notes/2019-10-16.md
Signed-off-by: Michael Ducy <michael@ducy.org>
=> Add October 16th 2019

meeting-notes/2019-10-30.md
=> office hours 2019 Oct 30th

meeting-notes/2019-11-13.md
=> new: office hours 13th November 2019

.github/ISSUE_TEMPLATE/discuss_pull_request.md
=> chore(.github): typo in the discuss PR template

meeting-notes/2019-12-11.md
Signed-off-by: Michael Ducy <michael@ducy.org>
=> Add 2019-12-11 Office Hours notes

meeting-notes/2020-01-08.md
=> new: add meeting minutes for Jan 8th 2020

meeting-notes/2020-01-22.md
=> new: meeting minutes for community call (22th Jan 2020)

OWNERS
Adding @kris-nova to OWNERS file.
=> update: OWNERS

meeting-notes/2020-02-13-infrastructure.md
=> new: meeting minutes for infra call 13th february 2020

meeting-notes/2020-02-19.md
=> new(meeting-notes): 2020 02 19 community call

README.md, meeting-notes/2020-03-11.md
=> docs: Updating README and notes from call

OWNERS
Just adding myself as owner/reviewer
=> new: owner (leogr)

meeting-notes/2020-03-25.md
=> docs: Adding call

README.md
=> docs(README): Adding hackmd link to readme

meeting-notes/2020-04-08.md
Meeting notes for the call.
Date: 4th April 2020
=> new(meeting-notes): 2020 04 08 call

meeting-notes/2020-04-15.md
Waiting for the recording link
/hold
=> new(meeting-notes): 2020 04 15

README.md
=> docs(README.md): remove hackmd template to avoid confusion

README.md, meeting-note-template.md
=> docs: add meeting note template here

meeting-notes/2020-04-29.md, meeting-notes/2020-04-30.md
Here the meeting minutes for April 29th.
This is still missing the youtube link since I wasn't able to login into the CNCF zoom to grab it.
I'll try to get some help on that side and update once I have it.
=> new(minutes): meeting notes 29th April 2020

meeting-notes/2020-05-06.md
Just the recording link is missing
/cc @kris-nova
=> new(meeting-notes): 2020 05 06

meeting-notes/2019-04-22.md
Add missing notes from 2020 04 22 call. 
Fixes #91 
/cc @kris-nova 
Please, double-check it and add the recording link
=> new(meeting-notes): 2020 04 22 call

meeting-notes/2020-05-20.md
=> new(meeting-notes): community call 20th May 2020

meeting-notes/2020-05-27.md
=> new: meeting minutes 2020-05-27

meeting-notes/2020-06-17.md
/cc @kris-nova 
Pls add YT recording link
=> new(meeting-notes): 2020 06 17

README.md
The new version of git broke some of my aliases - opening a PR to replace #102
=> feat(docs): Updating Zoom

meeting-notes/2020-07-01.md
=> update: meeting minutes July 1st 2020

meeting-notes/2020-07-08.md
Meeting notes for the today's community call.
/hold
since the recording is still processing.
=> new: meeting notes for community call (2020 July 08)

meeting-notes/2020-07-15.md
Waiting for the recording link
/hold
=> new(meeting-notes): 2020 07 15

meeting-notes/2020-07-22.md
=> new(meeting-notes): 2020 07 22

meeting-notes/2020-08-12.md
Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>
=> update: meeting notes for August 12th 2020

meeting-notes/2020-09-16.md
Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>
=> update: meeting notes for September 16th 2020

meeting-notes/2020-09-30.md
=> docs: meeting notes 2020-09-30

meeting-notes/2020-10-08-infra-wg.md
=> Infra wg notes

meeting-notes/2020-10-07.md
Just waiting for the recording link
/hold
P.S.
Thank you all for the birthday wishes! :hugs:
=> new: meeting note 2020-10-07

meeting-notes/2020-10-08-infra-wg.md
add maxgio92 to users who joined the meeting
Signed-off-by: maxgio92 <massimiliano.giovagnoli.1992@gmail.com>
=> feat(meeting-notes/2020-10-08-infra-wg.md): add user

OWNERS
i am requesting approval as a maintainer of the falco project. 
Reasons/Rationale:
• assist in the community tasks required to make falco even more successful
• Be the Community voice for various meetings
• Ensure our voice is being heard in the CNCF and beyond.
--Signed-off-by: POP <dan.papandrea@sysdig.com>
=> Adding pop as a maintainer

README.md
Co-Authored-By: Leonardo Di Donato <leodidonato@gmail.com>
=> update: calendar UTC

meeting-notes/2020-11-11.md
Co-Authored-By: Leonardo Di Donato <leodidonato@gmail.com>
Co-Authored-By: Leonardo Grasso <me@leonardograsso.com>
Co-Authored-By: Massimiliano Giovagnoli <massimiliano.giovagnoli.1992@gmail.com>
Co-Authored-By: Jonah Jones <jonahjones094@gmail.com>
Co-Authored-By: Spencer Krum <nibz@spencerkrum.com>
Co-Authored-By: Umang Vanjara <umang.vanjara@gmail.com>
=> docs(meeting-notes): meeting minutes for November 11th 2020

meeting-notes/2020-11-11.md
Signed-off-by: Leonardo Di Donato
=> recording for community call 2020-11-11

meeting-notes/2020-08-12-to-2020-12-16.md
=> update(meeting-notes): Add YT link for 2020-12-16 call

meeting-notes/2021-01-13.md
=> new(meeting-notes): 2021-01-13

meeting-notes/2021-01-20.md
=> new(meeting-notes): 2021-01-20

README.md
=> docs(README.md): update hackmd URL

meeting-notes/release-0.28.0.md
=> new(meeting-notes): archiving community calls notes regarding Falco 0.28

meeting-notes/release-0.28.1.md
=> new(meeting-notes): archiving community calls notes regarding Falco 0.28.1

meeting-notes/release-0.28.2.md
Signed-off-by: Michele Zuccala <michele@zuccala.com>
/assign @leogr
=> new(meeting-notes): archive meeting notes related to falco 0.28.2

meeting-notes/release-0.29.0.md
=> new(meeting-notes): archiving community calls notes regarding Falco 0.29

meeting-notes/release-0.29.1.md
=> new(meeting-notes): archiving notes falco 0.29.1

meeting-notes/release-0.30.0.md
Signed-off-by: Frederico Araujo <frederico.araujo@ibm.com>
**What type of PR is this?**
/kind documentation
**Any specific area of the project related to this PR?**
NONE
**What this PR does / why we need it**:
Archived meeting notes for Falco 0.30.0
**Which issue(s) this PR fixes**:
NONE
**Special notes for your reviewer**:
To be approved and merged after Falco 0.30.0 release
=> Archiving community calls notes regarding Falco 0.30.0

README.md
Signed-off-by: Anadee <anadeeyadav46@gmail.com>
Typo Corrected (Signed off commit)
=> Typo-Corrected

README.md
=> docs(README.md): use better URL for Falco slack

meeting-notes/release-0.32.1.md
Signed-off-by: Luca Guerra <luca@guerra.sh>
As per title. Archive meeting notes since 0.32.0
=> new(docs): add meeting notes for version 0.32.1

LICENSE
=> new: add LICENSE

meeting-note-template.md
=> docs(meeting-note-template.md): add community calls YT playlist

meeting-notes/release-0.32.2.md
Signed-off-by: Jason Dellaluce <jasondellaluce@gmail.com>
=> update(meeting-note): add v0.32.2 snapshot

meeting-notes/release-0.33.0.md
Signed-off-by: Luca Guerra <luca@guerra.sh>
As per title.
=> update(docs): archive meeting notes for 0.33.0

meeting-notes/release-0.33.1.md
Signed-off-by: Luca Guerra <luca@guerra.sh>
As per title.
=> new(docs): archive 0.33.1 meeting notes

community-appreciation-program.md
=> format update for section: How do I collect my swag? 

README.md
=>  docs(README): correct calendar `feed.ics` URL

meeting-notes/2023-06-08-Falco-Core-Maintainers.md
cc @falcosecurity/core-maintainers
=> docs(meeting-notes): Falco Core Maintainers monthly

meeting-notes/release-0.36.0.md
Following the release process.
=> new(meeting-notes): archive notes for 0.36.0

meeting-notes/release-0.36.2.md
/hold until the release pipeline finishes.
=> new(meeting-notes): added Falco 0.36.2 meeting notes.

meeting-notes/2023-11-02-Falco-Core-Maintainers.md
=> update(notes): add 2023-11-02-Falco-Core-Maintainers.md

meeting-notes/release-0.37.0.md
archive content of community calls for Falco 0.37.0
=> chore(meeting-notes): archive content of community calls

OWNERS
See https://github.com/falcosecurity/test-infra/pull/1487
=> docs(OWNERS): clean up no longer exiting user

meeting-notes/release-0.38.0.md
=> update(docs): add meeting notes for falco 0.38.0

README.md
Update the readme to reflect the last changes of the community call organization
=> update details for the community call
